#ifndef JULIAEDITOR_GLOBAL_H
#define JULIAEDITOR_GLOBAL_H

#include <QtCore/QtGlobal>

#if defined(JULIAEDITOR_LIBRARY)
#  define JULIAEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define JULIAEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JULIAEDITOR_GLOBAL_H

